-- Crie as tabelas executando este SQL no SQL Editor do Supabase

-- 1. Tabela de Clientes da Carteira
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  monthly_fee NUMERIC NOT NULL,
  contracted_hours NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabela de Configurações do Escritório
CREATE TABLE config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hourly_cost NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir o custo hora base inicial (id 1)
INSERT INTO config (hourly_cost) VALUES (50.00);

-- 3. Tabela de Logs do TimeSheet
CREATE TABLE logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  log_date TEXT NOT NULL,
  duration_seconds INTEGER NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Permissões (para funcionamento básico front-end sem auth complexa via RLS)
-- AVISO: Isso desativa RLS na tabela para testes. Para produção, configure RLS de acordo.
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE config DISABLE ROW LEVEL SECURITY;
ALTER TABLE logs DISABLE ROW LEVEL SECURITY;
